version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      lint-build-test:
        patterns:
        - "@playwright/test"
        - "@typescript-eslint/*"
        - "eslint-plugin-svelte"
        - "prettier-plugin-svelte"
        - "sass"
        - "svelte-check"
        - "typescript"
        - "vite"
        - "vitest"
