name: Build and Push

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  buildx:
    name: Build and push

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Build Stonky
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Build
      run: |
        npm install
        npm run lint
        npm run build

    # Tag the release
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

    # Create GitHub release
    - name: ZIP the package
      run: |
        cd build/
        zip -r stonky *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: Release ${{ steps.tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Attach ZIP to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/stonky.zip
        asset_name: stonky.zip
        asset_content_type: application/zip

    # Setup Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    # Login
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    # Build
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/j-be/stonky:${{ steps.tag.outputs.new_tag }}
        labels: ${{ steps.meta.outputs.labels }}
