name: Build and Push

on:
  push:
    branches:
    - main

jobs:
  buildx:
    name: Build and push

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build Stonky
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build
      run: |
        npm install
        npm run lint
        npm run build

    # Tag the release
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

    # Setup Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    # Login
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    # Build
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.tag.outputs.new_tag }}
        labels: ${{ steps.meta.outputs.labels }}
