name: Lint
on:
  push:
    branches:
    - '**'
    - '!main'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint
